export const HttpCodes40x = [
  { title: "400 - Bad Request", description: "", explanation: "" },
  { title: "401 - Unauthorized", description: "", explanation: "" },
  { title: "402 - Payment Required", description: "", explanation: "" },
  { title: "403 - Forbidden", description: "", explanation: "" },
  { title: "404 - Not Found", description: "", explanation: "" },
  { title: "405 - Method Not Allowed", description: "", explanation: "" },
  { title: "406 - Not Acceptable", description: "", explanation: "" },
  { title: "407 - Proxy Authentication Required", description: "", explanation: "" },
  { title: "408 - Request Timeout", description: "", explanation: "" },
  { title: "409 - Conflict", description: "", explanation: "" },
  { title: "410 - Gone", description: "", explanation: "" },
  { title: "411 - Length Required", description: "", explanation: "" },
  { title: "412 - Precondition Failed", description: "", explanation: "" },
  { title: "413 - Payload Too Large", description: "", explanation: "" },
  { title: "414 - URI Too Long", description: "", explanation: "" },
  { title: "415 - Unsupported Media Type", description: "", explanation: "" },
  { title: "416 - Range Not Satisfiable", description: "", explanation: "" },
  { title: "417 - Expectation Failed", description: "", explanation: "" },
  { title: "418 - I'm a Teapot!", description: "", explanation: "" },
  { title: "421 - Misdirect Request", description: "", explanation: "" },
  { title: "422 - Unprocessable Content", description: "", explanation: "" },
  { title: "423 - Locked", description: "", explanation: "" },
  { title: "424 - Failed Dependency", description: "", explanation: "" },
  { title: "425 - Too Early", description: "", explanation: "" },
  { title: "426 - Upgrade Required", description: "", explanation: "" },
  { title: "428 - Precondition Required", description: "", explanation: "" },
  { title: "429 - Too Many Requests", description: "", explanation: "" },
  { title: "431 - Request Header Fields Too Large", description: "", explanation: "" },
  { title: "451 - Unavailable for Legal Reasons", description: "", explanation: "" },
];
