export const HttpCodes40x = [
  { code: "400", title: "Bad Request", description: "", explanation: "" },
  { code: "401", title: "Unauthorized", description: "", explanation: "" },
  { code: "402", title: "Payment Required", description: "", explanation: "" },
  { code: "403", title: "Forbidden", description: "", explanation: "" },
  { code: "404", title: "Not Found", description: "", explanation: "" },
  { code: "405", title: "Method Not Allowed", description: "", explanation: "" },
  { code: "406", title: "Not Acceptable", description: "", explanation: "" },
  { code: "407", title: "Proxy Authentication Required", description: "", explanation: "" },
  { code: "408", title: "Request Timeout", description: "", explanation: "" },
  { code: "409", title: "Conflict", description: "", explanation: "" },
  { code: "410", title: "Gone", description: "", explanation: "" },
  { code: "411", title: "Length Required", description: "", explanation: "" },
  { code: "412", title: "Precondition Failed", description: "", explanation: "" },
  { code: "413", title: "Payload Too Large", description: "", explanation: "" },
  { code: "414", title: "URI Too Long", description: "", explanation: "" },
  { code: "415", title: "Unsupported Media Type", description: "", explanation: "" },
  { code: "416", title: "Range Not Satisfiable", description: "", explanation: "" },
  { code: "417", title: "Expectation Failed", description: "", explanation: "" },
  { code: "418", title: "I'm a Teapot!", description: "", explanation: "" },
  { code: "421", title: "Misdirect Request", description: "", explanation: "" },
  { code: "422", title: "Unprocessable Content", description: "", explanation: "" },
  { code: "423", title: "Locked", description: "", explanation: "" },
  { code: "424", title: "Failed Dependency", description: "", explanation: "" },
  { code: "425", title: "Too Early", description: "", explanation: "" },
  { code: "426", title: "Upgrade Required", description: "", explanation: "" },
  { code: "428", title: "Precondition Required", description: "", explanation: "" },
  { code: "429", title: "Too Many Requests", description: "", explanation: "" },
  { code: "431", title: "Request Header Fields Too Large", description: "", explanation: "" },
  { code: "451", title: "Unavailable for Legal Reasons", description: "", explanation: "" },
];
